// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG6rorc6LGiaCBhzwVVpXV3wGGdYI6Vrw',
    appId: '1:298998709480:web:597ec2678fa13815771d5d',
    messagingSenderId: '298998709480',
    projectId: 'talabatquiz',
    authDomain: 'talabatquiz.firebaseapp.com',
    storageBucket: 'talabatquiz.appspot.com',
    measurementId: 'G-M2459VJRKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJFf1d_bfNPN1EBVPJNjpeLqMmHR8Pq4M',
    appId: '1:298998709480:android:6c0c30f0d0d6981f771d5d',
    messagingSenderId: '298998709480',
    projectId: 'talabatquiz',
    storageBucket: 'talabatquiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3S2M75ERzM3Pu4kAKML4YwJtUxziyR5w',
    appId: '1:298998709480:ios:cb365becd5316bcf771d5d',
    messagingSenderId: '298998709480',
    projectId: 'talabatquiz',
    storageBucket: 'talabatquiz.appspot.com',
    iosBundleId: 'com.example.talabatQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3S2M75ERzM3Pu4kAKML4YwJtUxziyR5w',
    appId: '1:298998709480:ios:cb365becd5316bcf771d5d',
    messagingSenderId: '298998709480',
    projectId: 'talabatquiz',
    storageBucket: 'talabatquiz.appspot.com',
    iosBundleId: 'com.example.talabatQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG6rorc6LGiaCBhzwVVpXV3wGGdYI6Vrw',
    appId: '1:298998709480:web:1f927bec62d690e6771d5d',
    messagingSenderId: '298998709480',
    projectId: 'talabatquiz',
    authDomain: 'talabatquiz.firebaseapp.com',
    storageBucket: 'talabatquiz.appspot.com',
    measurementId: 'G-LEJPP3T99C',
  );
}
